
# Project ID for storing live version of
# summary DB of genotype frequencies
working_project: 'project-By6Zj080gV6QP2PXp88kYp65'

# Project ID for archival of previous versions
# of summary DB of genotype frequencies
archive_project: 'project-BxVXgF80VjVbZ1QfF0PKzFxk'

# Mapping of Contributing Agency
# to data-containing projects
contributors: {
    'NUHS': 'project-By6Yg9j0xx7P12342QVF09Yp',
    'PRISM': 'project-By6YgQj01Yv7GykB5QV19p21',
    'SGH': 'project-ByZGKX80xQG6B2ZJvjbxPBKq',
    'TTSH': 'project-By6Yg5Q089xv5X887QV1v3zX',
    'NUS': 'project-ByV8kV00Xqb8Fz5Y1Vz9y59Z',
    'GIS': 'project-Bz2696Q0j4zP7B0pXJ19b17k'
}

env:
  global:
    secure: "rRCI4+ghwWdRqsjP5U0PFmeOmaN8QCpOb3LSwZPjPpWhfnOjYItmLsGSIWDugYf4rehl+jnTGyQLOOrmFX8vW+TPhgDygMXlTI7FGseJcQB9l7uCV5bfaAMU6/gH1CgBk5feKYJLrS16a6UIFgq93AZ7DpFAuZ899aOgm7D305MEf3/qjDhXYfbOcjF66Z85L97BZnXMnX+XM0ZBZsDimx6ELeKZ5hwjdo5nECqYRzENc0sjam2pne+4u/IvAuyO5dlUUiup9P6inUfX6DQ2Ymc9yp5BxrTjZSMDkTa/qIcSMdsYmPdKmsSksxtVFD/2z9Fd0yKho4sohsUQuty1cbQWkEQctBNeK0/CXPOT66uSzx2WoNLsLHs/3q27MKcMUSjSeYIE5Q89sETlkE4pRbwf+6AuVLG/4roEMc5qv2FurVDXdC2ytKO2wyuTKar7wZ0TuCYsQoRkyyKp+Ws2yoltzzYXt7d7623+Fc6n568CP9tfTd/Yz52KGdT01RW1U5yMWiUhrkKXBQkphOLxatJMjMYoNfOj94+AsszAPDWGoeaCH/gs7IpZ4Rky2Jh5NEcgLKjdO823dhcb3TfK2rR9oh0vJHuUrVSo/fouS4MsfuUDz4eNky8XpCVu4kVmEPqzyy1a9PtU5bOnGjIn9wIzmdCNhYiik4/Y29Kv0ZM="