
# Project ID for storing live version of
# summary DB of genotype frequencies
working_project: 'project-BxjkyJ00jFZ40P5vk4X8yY9V'

# Project ID for archival of previous versions
# of summary DB of genotype frequencies
archive_project: 'project-Bxjkybj0498355qGZJyB1BqJ'

# Mapping of mappings of Contributing Agency
# to data-containing projects
contributors: {
    'TTSH': 'project-BxfgGP00gZ5XvPK6q5bbZ3y5',
    'PRISM': 'project-BxfgGY80fpjXvPK6q5bbZ3z0'
}
