#!/bin/bash
# appending_queries_VCF 0.0.1
# Generated by dx-app-wizard.
#
# See https://wiki.dnanexus.com/Developer-Portal for tutorials on how
# to modify this file.

main() {

    echo "Value of input_vcf: '$input_vcf'"
    echo "Value of queried_vcf: '${queried_vcf[@]}'"
    echo "Value of database_name: '$database_name'"

    # The following line(s) use the dx command-line tool to download your file
    # inputs to the local file system using variable names for the filenames. To
    # recover the original filenames, you can use the output of "dx describe
    # "$variable" --name".

    ## download
    
    dx download "$input_vcf" -o "$input_vcf_name"
    mkdir allqueried
    cd allqueried
    for i in ${!queried_vcf[@]}
    do
        dx download "${queried_vcf[$i]}"
        ls
    done
    
    if [ -n "$database_name" ]; then
        echo 'rename'
        IFS=', ' read -r -a array <<< "$database_name"
        for i in ${!queried_vcf[@]}
        do
            mv "${queried_vcf_name[$i]}" "${array[$i]}"
        done
    fi
    
    echo 'append to list'
    all_querie=''
    for i in $(ls)
        do
            all_queried="$all_queried $i"
        done
    mv ../"$input_vcf_name" .
    
    echo 'merge'
    python ~/VCF_info_appending.py "$input_vcf_name" $all_queried > "${input_vcf_prefix}.querymarge.vcf" 
    
    echo 'output'
    output_vcf=$(dx upload "${input_vcf_prefix}.querymarge.vcf"  --brief)
    dx-jobutil-add-output output_vcf "$output_vcf" --class=file
}
